'use strict';

module.exports = {
    GET_TASKS: 'GET_TASKS',
    GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
    GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
    GET_TASKS_ERROR: 'GET_TASKS_ERROR',

    ADD_TASK: 'ADD_TASK',
    ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_ERROR: 'ADD_TASK_ERROR',

    DELETE_TASK: 'DELETE_TASK',
    DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',

    EDIT_TASK: 'EDIT_TASK',
    EDIT_TASK_REQUEST: 'EDIT_TASK_REQUEST',
    EDIT_TASK_SUCCESS: 'EDIT_TASK__SUCCESS',
    EDIT_TASK_ERROR: 'EDIT_TASK__ERROR',

    COMPLETE_TASK: 'COMPLETE_TASK',
    COMPLETE_TASK_REQUEST: 'COMPLETE_TASK_REQUEST',
    COMPLETE_TASK_SUCCESS: 'COMPLETE_TASK_SUCCESS',
    COMPLETE_TASK_ERROR: 'COMPLETE_TASK_ERROR',

    COMPLETE_ALL: 'COMPLETE_ALL',
    COMPLETE_ALL_REQUEST: 'COMPLETE_ALL_REQUEST',
    COMPLETE_ALL_SUCCESS: 'COMPLETE_ALL_SUCCESS',
    COMPLETE_ALL_ERROR: 'COMPLETE_ALL_ERROR',

    DELETE_COMPLETED: 'DELETE_COMPLETED',
    DELETE_COMPLETED_REQUEST: 'DELETE_COMPLETED_REQUEST',
    DELETE_COMPLETED_SUCCESS: 'DELETE_COMPLETED_SUCCESS',
    DELETE_COMPLETED_ERROR: 'DELETE_COMPLETED_ERROR',

    LOGIN: 'LOGIN',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    REGISTER: 'REGISTER',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    LOGOUT: 'LOGOUT',
    NAVIGATE: '@@router/LOCATION_CHANGE',
    HISTORY_NAVIGATE: '@@router/CALL_HISTORY_METHOD'
};
